# Generated by Django 5.2.14 on 2026-05-12 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daibunrui',
            fields=[
                ('code', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': '大分類',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Chubunrui',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('daibunrui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chubunrui_list', to='core.daibunrui')),
            ],
            options={
                'verbose_name': '中分類',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Shobunrui',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('chubunrui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shobunrui_list', to='core.chubunrui')),
            ],
            options={
                'verbose_name': '小分類',
                'ordering': ['code'],
            },
        ),
    ]
