# Generated by Django 5.2.14 on 2026-05-12 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daibunrui',
            options={'ordering': ['code'], 'verbose_name': '大分類'},
        ),
        migrations.RemoveField(
            model_name='daibunrui',
            name='order',
        ),
    ]
