# Generated by Django 5.2.14 on 2026-05-13 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_daibunrui_options_remove_daibunrui_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chubunrui',
            options={'ordering': ['code'], 'verbose_name': '中分類', 'verbose_name_plural': '中分類'},
        ),
        migrations.AlterModelOptions(
            name='daibunrui',
            options={'ordering': ['code'], 'verbose_name': '大分類', 'verbose_name_plural': '大分類'},
        ),
        migrations.AlterModelOptions(
            name='shobunrui',
            options={'ordering': ['code'], 'verbose_name': '小分類', 'verbose_name_plural': '小分類'},
        ),
    ]
